# Numpy
- 수학, 과학 계산용 패키지
- 성능 : 파이썬 리스트보다 빠름
- 메모리사이즈 : 파이썬 리스트보다 적은 메모리 사용
- 빌트인 함수 : 선형대수, 통계관련 여러 함수 내장
- 1차원 : 벡터
- 2차원 : 행렬

In [1]:
!pip install numpy  # 외부모듈 설치할때 앞에 ! 붙여주기

## 1. array

In [2]:
import numpy as np

### 1.1. np.array()로 생성하기

In [6]:
arr1 = np.array([1,2,3,4])
print(arr1, type(arr1))
arr1

[1 2 3 4] <class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [7]:
[1,2,3,4] 

[1, 2, 3, 4]

In [10]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
print('arr2의 ndim :', arr2.ndim ) # arr2의 차원
print('arr2의 shape :', arr2.shape) # arr2의 shape
print('arr2의 size :', arr2.size) # arr2의 원소 갯수


arr2의 ndim : 2
arr2의 shape : (2, 4)
arr2의 size : 8


### 1.2. list 생성하기

In [15]:
mylist1 = [1,2,3,4]
mylist2 = [[1,2,3,4], [5,6,7,8]]

In [16]:
arr1 = np.array(mylist1)
arr1

array([1, 2, 3, 4])

In [17]:
arr2 = np.array(mylist2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1.3.  np.arange()로 생성하기

- 우리는 순차적인 값을 생성할 때가 많다.

1. 회원에 대한 가입 번호 부여 (1번 회원부터 순차적으로~)
2. 100개 한정 판매 상품에 대한 고유 번호 부여

등등.. 이 밖에도 데이터 관리를 위한 인덱스를 차례대로 부여하는 것은 매우 흔한 일이다.
(심지어, 엑셀에서도 왼쪽 행에 1번부터~ 쭈욱 부여된다.)

#### 1.3.1. 순서대로 리스트에 값을 생성하려면?

1~10까지 값을 생성하려면?

In [20]:
arr = [1,2,3,4,5,6,7,8,9,10]
arr

arr2 = [x for x in range(1,11)]
arr2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### 1.3.2. arange()를 사용해서 쉽게 생성하기

첫번째 인자에는 **start 이상**, 두번째 인자에는 **stop의 미만**

In [21]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr = np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 1.3.3. keyword 인자를 사용해보기

keyword 인자는 파라미터(인자)의 keyword를 지정해줌으로썬 순서 없이 지정해 줄 수 있습니다.

In [23]:
arr = np.arange(start = 1,stop = 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr = np.arange(stop=11, start=1, step=3)
arr

array([ 1,  4,  7, 10])

**연습문제) 1~10 사이의 값 중 홀수만 생성하시오.**

In [27]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

### 1.4. array를 쉽게 만들어주는 기타 함수들

#### 1.4.1. np.ones(), np.zeros()
- shape을 tuple형식으로 넣어준다.

In [30]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [37]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
np.zeros((2,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

#### 1.4.2. np.empty(), np.full()
- np.empty : 초기화되지 않은 값으로 배열을 생성. 메모리도 초기화되지 않기 때문에 예상하지 못한 쓰레기 값이 들어감

In [41]:
np.empty((3,4))

array([[1.15267425e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.42349297e-052, 4.31244270e-033,
        1.17607618e-047],
       [1.63105556e+185, 4.17920788e-062, 1.95326001e+184,
        1.93314549e-076]])

In [42]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

#### 1.4.3. np.eye()

- 단위행렬 생성

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 1.4.4. np.linspace()
- np.linspace(start,stop,num)
- start ~ stop 사이에 숫자를 num개 만들기 (같은 간격으로)

In [44]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [45]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

#### 1.4.5. reshape()

In [51]:
x = np.arange(1,21)
print(x)
print(x.shape)

# 2차원 배열로 바꾸고 싶다면
x.reshape(4,5)   # >> 갯수가 맞아야 바뀜

y = x.reshape(2,5,2)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


In [65]:
x = np.arange(1,50,2).reshape(5,5)
print(x)

y = np.arange(3,101,3).reshape(3,11)
print(y)


[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 3  6  9 12 15 18 21 24 27 30 33]
 [36 39 42 45 48 51 54 57 60 63 66]
 [69 72 75 78 81 84 87 90 93 96 99]]


### 1.5. random 서브모듈

#### 1.5.1. rand()
- 0~1사이의 분포로 랜덤한 ndarray 생성

In [66]:
np.random.rand(2,3)

array([[0.02450207, 0.63655852, 0.09395298],
       [0.97309643, 0.97247493, 0.3912152 ]])

In [67]:
np.random.rand(10)

array([0.49405974, 0.71532853, 0.56425518, 0.55679692, 0.88781538,
       0.29933943, 0.85581329, 0.66612408, 0.85198704, 0.18857511])

#### 1.5.2. randn()
- n : normal distrbution(정규분포)
- 정규분포로 샘플링된 램덤 ndarray 생성

In [72]:
np.random.randn(3,4)
np.random.randn(5)

array([ 0.13238165,  0.20659167,  0.56528158, -0.55230616,  1.26884115])

#### 1.5.3. randint()
- 특정정수 사이에서 랜덤하게 샘플링

In [73]:
np.random.randint(1,100, size=(3,4))


array([[31, 62, 13, 32],
       [49, 60, 72, 89],
       [96, 58, 16, 54]])

#### 1.5.4. seed()
- 랜덤한 값을 동일하게 다시 생성하고자 할때

In [77]:
np.random.rand(3,4)

array([[0.07513574, 0.33498653, 0.74757455, 0.26548172],
       [0.74749917, 0.17230466, 0.45674398, 0.12984122],
       [0.08672684, 0.84086006, 0.22054821, 0.09079957]])

In [79]:
np.random.seed(100)
print(np.random.rand(3,4))
print()
np.random.seed(200)
print(np.random.rand(3,4))
print()
np.random.seed(100)
print(np.random.rand(3,4))

[[0.54340494 0.27836939 0.42451759 0.84477613]
 [0.00471886 0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195 0.20920212]]

[[0.94763226 0.22654742 0.59442014 0.42830868]
 [0.76414069 0.00286059 0.35742368 0.90969489]
 [0.45608099 0.98180271 0.86735699 0.98602751]]

[[0.54340494 0.27836939 0.42451759 0.84477613]
 [0.00471886 0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195 0.20920212]]


#### 1.5.5. choice()
- 주어진 1차원 ndarray()로 부터 랜덤으로 샘플링
- 정수가 주어진 경우 np.arrange(숫자)로 간주
- 

In [83]:
#0~99사이의 ndarray 생성  (중복 가능)
np.random.choice(100, size=(3,4))

array([[38, 44, 18, 64],
       [56, 34, 53, 74],
       [17, 72, 13, 30]])

In [84]:
x = np.array([1,2,3,1.5, 2.5, 4.9])
np.random.choice(x, size=(2,3))

array([[2. , 4.9, 2.5],
       [3. , 1. , 1.5]])

In [92]:
# 0~100,사이의 중복되지 않은 랜덤한 숫자로 3X4 array를 만든다면?
np.random.choice(100, size=(3,4),replace=False)

array([[57, 87,  5, 63],
       [49, 26, 16, 21],
       [36, 18, 93,  6]])

## 2. array에서의 data 타입
- array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용 됩니다.

### 2-1. list에서의 data 타입

In [ ]:
# list에서는 자료형이 섞여 있어도 상관없다.
mylist = [1, 3.14, '테디', '1234']
mylist

### 2-2. array에서의 data 타입

### case 1. int와 float 타입이 혼재된 경우
- float형으로 바뀐다

In [93]:
arr = np.array([1, 2, 3.14, 7.6])
arr

array([1.  , 2.  , 3.14, 7.6 ])

### case 2. int와 float 타입이 혼재되었으나, dtype을 지정한 경우
- 지정한 타입으로 바뀐다.

In [94]:
arr = np.array([1, 2, 3.14, 7.6], dtype=int)
arr

array([1, 2, 3, 7])

### case 3. int와 str 타입이 혼재된 경우
- 문자형으로 바뀐다.
- <U32 : 유니코드

In [100]:
arr = np.array([1, 2, 3.14, 'Hello'])
arr

array(['1', '2', '3.14', 'Hello'], dtype='<U32')

### case 4. int와 str 타입이 혼재되어 있고 int로 dtype을 지정한 경우

In [101]:
arr = np.array([1, 2, 3.14, 'Hello'],dtype=int)
arr

ValueError: invalid literal for int() with base 10: 'Hello'

In [102]:
arr = np.array([1, 2, 3.14, '1234'],dtype=int)
arr

array([   1,    2,    3, 1234])

## 3. ndarry 인덱싱 & 슬라이싱 
- 개념적으로는 list의 인덱싱과 슬라이싱과 동일
- **,** 를 사용하여 각 차원의 인덱스에 접근 가능

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.shape

### 3.1. 인덱싱(Indexing)

#### 3.1.1. 1차원 array

In [16]:
arr = np.arange(10)

print(arr)
print(arr[0])
print(arr[5])
#print(arr[10])
print(arr[-1])
print(arr[-10])

[0 1 2 3 4 5 6 7 8 9]
0
5
9
0


#### 3.1.2. 2차원 array


In [104]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])
arr2d.shape

(3, 4)

**arr2d[행, 열]**
- 하나의 원소를 뽑고 싶으면 인덱스가 **[행, 열]** 의 형태이어야 한다

In [105]:
arr2d[0]

array([1, 2, 3, 4])

In [106]:
arr2d[0,2]


3

In [107]:
arr2d[1,-1]


8

#### 3.1.3. 3차원 array

In [108]:
arr3d = np.arange(36).reshape(3,4,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [109]:
arr3d[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [110]:
arr3d[1,0]

array([12, 13, 14])

In [111]:
arr3d[2,1,0]

27

In [112]:
arr3d[2,3,2]

35

### 3.2. 슬라이싱(Slicing)
- 리스트, 문자열 slicing과 동일한 개념으로 사용
- **,** 를 사용하여 각 차원 별로 슬라이싱 가능
- 인덱싱은 차원의 변화가 있지만 슬라이싱은 차원의 변화는 없다

#### 3.2.1. 1차원 array

In [125]:
arr = np.arange(10)

# 전부다
print(arr)
print(arr[:])
print(arr[0:10])
print(arr[-10:])

# 1부터 끝까지
print(arr[1:])

# 0부터 4까지
print(arr[:5])

# 1부터 4까지
print(arr[1:5])

# 0부터 8까지
print(arr[:9])
print(arr[:-1])

# 거꾸로
print(arr[::-1])

# 짝수만
print(arr[2::2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[1 2 3 4]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[9 8 7 6 5 4 3 2 1 0]
[2 4 6 8]


#### 3.2.2. 2차원 array
- **np.array[행,렬]** 

In [127]:
arr2d = np.arange(1,13).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
# (2, 3) 값을 가져오기 -> 인덱싱
arr2d[2,3]

12

In [129]:
#0행~1행, 모든 열 슬라이싱
arr2d[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
# 모든행, 1열~3열 슬라이싱
arr2d[:,1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [132]:
#0행~1행, 2열~끝까지 슬라이싱
arr2d[:2,2:]

array([[3, 4],
       [7, 8]])

**인덱싱, 슬라싱 혼합**

In [135]:
# 인덱싱, 슬라이싱 혼합
print(arr2d[0, :])

# 슬라이싱
print(arr2d[:1,:])

[1 2 3 4]
[[1 2 3 4]]


In [136]:
# 인덱싱, 슬라이싱 혼합
print(arr2d[:,2])

# 슬라이싱
print(arr2d[:,2:3])

[ 3  7 11]
[[ 3]
 [ 7]
 [11]]


#### 3.2.3. 3차원 array

In [148]:
arr3d = np.arange(54).reshape(2, 9, 3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [150]:
#0~5까지 가져오고 싶다면? 슬라이싱 ->차원 유지
print(arr3d[:1,:2,:])

#인뎅싱 혼합 -> 차원 변화
print(arr3d[0, :2, :]) 

[[[0 1 2]
  [3 4 5]]]
[[0 1 2]
 [3 4 5]]


In [149]:
# 43,44 가져오고 싶다면?
# 슬라이싱 -> 3차원
print(arr3d[1:,5:6,1:])


# 인덱싱, 슬라이싱, 슬라이싱 -> 2차원
print(arr3d[1,5:6,1:])

# 인덱싱, 인덱싱, 슬라이싱 -> 1차원
print(arr3d[1,5,1:])

[[[43 44]]]
[[43 44]]
[43 44]


## 4. Fancy 인덱싱

- fancy 인덱싱은 범위가 아닌 **특정 index의 집합의 값을 선택하여 추출**하고 싶을 때 활용
- **[추출하고 싶은 인덱스]** 

### 4.1.  1차원 array

In [153]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])
idx = [1, 3, 5]

print(arr)
print(arr[idx])
print(arr[[1,3,5]])

[10 23  2  7 90 65 32 66 70]
[23  7 65]
[23  7 65]


### 4.2.  2차원 array

In [167]:
arr2d = np.arange(1,13).reshape(3,4)
print(arr2d)
print('-'*20)

# 0행~1행 값 가져오기
print(arr2d[[0,1],:])
print(arr2d[:2, :])
print('-'*20)
#1열~3열 값 가져오기
print(arr2d[:,[1,2,3]])
print(arr2d[:,1:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
[ 2  7 12]


## 5. ndarray 데이터 형태 바꾸기

### 5.1 ravel()
- 다차원 배열을 1차원으로 변경
- 'order'파라미터
    - **'C'** : row 우선변경
    - **'F'** : column 우선변경

In [177]:
x = np.arange(15).reshape(3,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [178]:
# ravel은 ndarrary 의 멤버함수 이면서 -> x.ravel()
# np안에 일반함수로도 존재한다. ->np.ravel(x) 
# 차이는 없다. 편한걸로
# 다차원의 배열을 쭉~~펴서 1차원으로 만들어 주는 기능
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [179]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [181]:
print(x)
temp = np.ravel(x)
print(temp)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [183]:
# 값을 유지해서 같이 바뀐다. 복사본을 만드는게 아니다.
temp[0] = 100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [27]:
x = np.arange(15).reshape(3,5)
print(x)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [184]:
# 행으로 펴집. 기본 C로 되어 있음
np.ravel(x)
np.ravel(x,order='C')

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [186]:
# 열로 펴짐
print(x)
np.ravel(x,order='F')

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


array([100,   5,  10,   1,   6,  11,   2,   7,  12,   3,   8,  13,   4,
         9,  14])

### 5.2. flatten
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점: copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
 - 데이터의 변경이 중요하지 않다 -> 아무거나!! , 중요하다 -> flatten 사용
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경

In [188]:
y = np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [189]:
#flatten은 멤버 함수로만 있다.
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [190]:
# 복사를 해서 쓰는거라 y값 바뀌지 않는다.
temp2 = y.flatten()

temp2[0] = 200
print(y)
print(temp2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[200   1   2   3   4   5   6   7   8   9  10  11  12  13  14]


In [194]:
# 행기준. 디폴트
temp2 = y.flatten()
print(temp2)

temp2 = y.flatten(order='C')
print(temp2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [192]:
# 열기준. 
temp2 = y.flatten(order='F')
print(temp2)

[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


### 5.3. reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능


In [170]:
x = np.arange(36)
print(x)
print(x.shape)  
print(x.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [171]:
# 값의 곱이 원래의 값과 같아야 한다.
x.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [172]:
# 하나의 값이 확정되면(6) 나머지는 알아서 정해주는 기능. 정확한 값을 모를때
x.reshape(6,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [174]:
x.reshape(-1,12)  # 앞이든 뒤든 -1 붙이면 알아서 해줌

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [175]:
y = x.reshape(3,3,4)
print(y)
print(y.ndim)
print(y.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
3
(3, 3, 4)


In [176]:
# 다른 코드를 볼때 -1을 많이 보게 된다. 당황하지 말자!!!!
k = x.reshape(3,3,-1)
print(k)
print(k.ndim)
print(k.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
3
(3, 3, 4)
