In [1]:
import numpy as np

## numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

## 1. 연산함수
- add, substract, multiply, divide

In [8]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
z = np.arange(16).reshape(4,4)

print(x)
print(y)
print(z)
print(x.shape, y.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.80831824 0.46773612 0.12327743 0.11126634 0.18956051]
 [0.93858887 0.89761735 0.04433372 0.85680071 0.80131872]
 [0.81163342 0.53475365 0.58881785 0.003759   0.07888446]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(3, 5) (3, 5)


In [6]:
# 인덱스가 같은 원소끼리 더해짐. sahpe이 다른 경우는 error!
np.add(x,y)

array([[ 0.19578611,  1.59285511,  2.75468597,  3.59320497,  4.93016512],
       [ 5.56448001,  6.87696318,  7.45597332,  8.04505814,  9.26233949],
       [10.57616523, 11.31619907, 12.32887876, 13.2914329 , 14.77522678]])

In [11]:
print(x)
print(z)
add(x,z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


NameError: name 'add' is not defined

In [15]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)
np.subtract(x,y)
np.multiply(x,y)
np.divide(x,y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.05158947 0.39249207 0.56776546 0.41349564 0.64393504]
 [0.56726008 0.67889094 0.05474841 0.49170921 0.29992615]
 [0.736352   0.38474019 0.93058111 0.5622254  0.36370273]]


array([[  0.        ,   2.54782215,   3.52258133,   7.25521549,
          6.21180669],
       [  8.81429908,   8.83794383, 127.85760579,  16.26977863,
         30.00738723],
       [ 13.58046161,  28.5907226 ,  12.89516828,  23.12239878,
         38.49297508]])

In [16]:
# 사칙연산은 함수보다는 바로 연산자를 이용한다.
# 기본적으로는 두 배열의 shape을 같아야 하는것만 주의(나중에 브로드캐스트 배운다,)
x+y

array([[ 0.05158947,  1.39249207,  2.56776546,  3.41349564,  4.64393504],
       [ 5.56726008,  6.67889094,  7.05474841,  8.49170921,  9.29992615],
       [10.736352  , 11.38474019, 12.93058111, 13.5622254 , 14.36370273]])

In [17]:
x-y

array([[-0.05158947,  0.60750793,  1.43223454,  2.58650436,  3.35606496],
       [ 4.43273992,  5.32110906,  6.94525159,  7.50829079,  8.70007385],
       [ 9.263648  , 10.61525981, 11.06941889, 12.4377746 , 13.63629727]])

In [18]:
x*y

array([[ 0.        ,  0.39249207,  1.13553092,  1.24048693,  2.57574017],
       [ 2.8363004 ,  4.07334565,  0.38323884,  3.93367368,  2.69933531],
       [ 7.36351995,  4.23214207, 11.16697331,  7.30893026,  5.09183818]])

In [19]:
x/y

array([[  0.        ,   2.54782215,   3.52258133,   7.25521549,
          6.21180669],
       [  8.81429908,   8.83794383, 127.85760579,  16.26977863,
         30.00738723],
       [ 13.58046161,  28.5907226 ,  12.89516828,  23.12239878,
         38.49297508]])

**행렬(Matrix) 곱셈**
- **np.dot(array1, array2)** : 일반함수
- **array1.dot(array2)** : numpy.arrary type 멤버함수 
- **array1 @ array2**

In [24]:
np.dot(x,y)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [2]:
x = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])
y = np.array([[1, 2],
              [3, 4],  
              [5, 6]])
x.shape, y.shape

((3, 3), (3, 2))

In [22]:
np.dot(x,y)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [23]:
x.dot(y)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [24]:
x@y

array([[22, 28],
       [22, 28],
       [31, 40]])

In [85]:
# 1행 1열
1*1 + 2*3 + 3*5

22

In [86]:
# 1행 2열
1*2 + 2*4 + 3*6

28

## 2. 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [3]:
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
#평균
# 멤버함수, 일반함수 둘다 가능. 모두 다되는건 아니다. 기본적인것은 있다.
# 왠만하면 np안에 있다. 멤버 함수로 없는 경우가 있다.

np.mean(y)  # 멤버함수

3.5

In [5]:
y.mean()  # 일반함수

3.5

In [6]:
# 최대값
np.max(y)

6

In [7]:
y.max()

6

In [8]:
# 가장 큰 값의 인덱스를 가져올 때
#다차원이지만 1차원으로 계산해서 인덱스를 가지고 온다.  y = [1, 2, 3, 4, 5, 6] 으로 생각 > 6의 인덱스 : 5

np.argmax(y)


5

In [9]:
# 우리가 loop를 돌려서 구했던 것들 대부분 np 함수를 이용해서 구할 수 있다.
# 분산,    중앙값,       표준편차
np.var(y), np.median(y), np. std(y)

(2.9166666666666665, 3.5, 1.707825127659933)

## 3. 집계함수
 - 합계: sum()
 - 누적합계(Cumulative Sum): cumsum()

In [10]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
np.sum(y)

21

In [14]:
# 앞에 원소랑 자신의 합을 나타냄. 누적된 값을 그래프로 그릴때 유용
np.cumsum(y)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [16]:
# 각 행의 열끼리 더함. 파이썬 내장함수
sum(y)

array([ 9, 12])

In [18]:
# axis는 기본적으로 None -> 전체의 합을 구한다.
# axis가 0이면 행의 합을 구함 y(0,0)+y(1,0)+y(2,0),.....,y(0,4)+y(1,4)+y(2,4)
print(y)
np.sum(y, axis=0)

[[1 2]
 [3 4]
 [5 6]]


array([ 9, 12])

In [19]:
# axis가 1이면 축의 합을 구함 y(0,0)+y(0,1)+y(0,2)+..+y(0,4), y(1,0)+...y(1,4), y(2,0)+..+y(2,4)
np.sum(y, axis=1)

array([ 3,  7, 11])

In [26]:
print(x)
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2 3]
 [1 2 3]
 [2 3 4]]
[ 4  7 10]
[6 6 9]


## 4. any(), all()
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [20]:
z = np.random.randn(10)
print(z)

[ 1.1461044  -0.81894693 -0.19276526  0.35143974 -0.04626315  0.60685285
  1.86797072  0.59371881 -1.02247648 -0.71890333]


In [21]:
z > 0

array([ True, False, False,  True, False,  True,  True,  True, False,
       False])

In [22]:
# 조건이 하나라도 맞으면 참
np.any(z > 0)

True

In [23]:
# 조건을 모두 만족해야 참
np.all(z > 0)

False

In [24]:
np.all(z != 0)

True

## 5. where()
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우
 - numpy에서 많이 쓰이는 함수 중 하나

In [27]:
z = np.random.randn(10)
print(z)

[-0.43796723  0.90278853  0.42927002 -3.10473282 -1.06931606 -0.19280395
 -1.06220748  1.97638608 -0.20844765  0.30710293]


In [28]:
# 10개의 벡터에서 0보다 크면 그 값을 쓰고 아니면 0으로 바꾸고 싶어요.

np.where(z>0, z, 0)

array([0.        , 0.90278853, 0.42927002, 0.        , 0.        ,
       0.        , 0.        , 1.97638608, 0.        , 0.30710293])

In [30]:
# 파이썬 이용하면 loop돌려서 비교하고 바꾸고..np 이용하면 쉽고 빠르게 사용가능!! 빠른성능, 적은 메모리
lista = []

for i in z :
    if i>0 :
        lista.append(i)
    else : 
        lista.append(0)

        
arr1 = np.array(lista)
arr1


array([0.        , 0.90278853, 0.42927002, 0.        , 0.        ,
       0.        , 0.        , 1.97638608, 0.        , 0.30710293])

## 6. 정렬함수
### 6.1. 1차원 정렬

In [31]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 7, 9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

**np.sort(arr)**
- 기본적으로 오름차순 정렬
- 내림차순 : **np.sort(arr)[::-1]** 

In [33]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.sort(arr)[-1:-11:-1]
np.sort(arr)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

하지만, 이 값들은 **유지가 되지 않습니다**!

In [36]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [37]:
arr2 = np.sort(arr)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# sort 한 상태로 유지시키고 싶다면...
arr.sort()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 6.2. N차원 정렬

In [39]:
arr2d = np.array([[3, 8, 6, 5], 
                  [7, 4, 2, 1],
                  [10, 9, 12, 11]])
arr2d.shape

(3, 4)

#### 6.2.1. 열 정렬 (왼쪽에서 오른쪽으로)

In [40]:
np.sort(arr2d, axis=1)

array([[ 3,  5,  6,  8],
       [ 1,  2,  4,  7],
       [ 9, 10, 11, 12]])

In [42]:
np.sort(arr2d, axis=1)[::-1,:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  4,  7],
       [ 3,  5,  6,  8]])

In [43]:
np.sort(arr2d, axis=1)[:,::-1]

array([[ 8,  6,  5,  3],
       [ 7,  4,  2,  1],
       [12, 11, 10,  9]])

In [44]:
np.sort(arr2d, axis=1)[::-1,::-1]

array([[12, 11, 10,  9],
       [ 7,  4,  2,  1],
       [ 8,  6,  5,  3]])

#### 6.2.2. 행 정렬 (위에서 아래로)

In [45]:
print(arr2d)
np.sort(arr2d, axis=0)

[[ 3  8  6  5]
 [ 7  4  2  1]
 [10  9 12 11]]


array([[ 3,  4,  2,  1],
       [ 7,  8,  6,  5],
       [10,  9, 12, 11]])

In [46]:
np.sort(arr2d, axis=0)[::-1,:]

array([[10,  9, 12, 11],
       [ 7,  8,  6,  5],
       [ 3,  4,  2,  1]])

In [47]:
np.sort(arr2d, axis=0)[:,::-1]

array([[ 1,  2,  4,  3],
       [ 5,  6,  8,  7],
       [11, 12,  9, 10]])

In [48]:
np.sort(arr2d, axis=0)[::-1,::-1]

array([[11, 12,  9, 10],
       [ 5,  6,  8,  7],
       [ 1,  2,  4,  3]])

### 6.3. index를 반환하는 argsort

- 정렬된 값을 반환하는 것이 아닌 index를 반환

In [49]:
arr2d = np.array([[3, 8, 6, 5], 
                  [7, 4, 2, 1],
                  [10, 9, 12, 11]])


#### 6.3.1. 열 정렬 (왼쪽에서 오른쪽으로)

In [52]:
print(arr2d)
np.argsort(arr2d, axis=1)

[[ 3  8  6  5]
 [ 7  4  2  1]
 [10  9 12 11]]


array([[0, 3, 2, 1],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

#### 6.3.2. 행 정렬

In [54]:
print(arr2d)
np.argsort(arr2d, axis=0)

[[ 3  8  6  5]
 [ 7  4  2  1]
 [10  9 12 11]]


array([[0, 1, 1, 1],
       [1, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)

# 7. 기타함수

In [55]:
z = np.random.randn(10)
print(z)

[ 0.69988979 -0.42133447  1.31066688 -0.07247368  0.53939768  0.29582741
  0.67036912  0.18904462  0.78942759 -0.66398672]


In [56]:
# 절대값
np.abs(z)

array([0.69988979, 0.42133447, 1.31066688, 0.07247368, 0.53939768,
       0.29582741, 0.67036912, 0.18904462, 0.78942759, 0.66398672])

In [57]:
# 부호찾기
np.sign(z)

array([ 1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.])

In [58]:
np.sin(1), np.cos(1), np.tan(1)

(0.8414709848078965, 0.5403023058681398, 1.5574077246549023)